# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infinitive',
            name='english_name',
            field=models.CharField(max_length=125),
        ),
    ]
