# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_auto_20151229_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='infinitive',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
