# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0003_infinitive_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irregular', models.BooleanField(default=False)),
                ('form_1s', models.CharField(max_length=80)),
                ('form_2s', models.CharField(max_length=80)),
                ('form_3s', models.CharField(max_length=80)),
                ('form_1p', models.CharField(max_length=80)),
                ('form_2p', models.CharField(max_length=80)),
                ('form_3p', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Gerund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerund', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('mood_english', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pastparticiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastparticiple', models.CharField(max_length=50)),
                ('pastparticiple_english', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=50)),
                ('tense_english', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='infinitive',
            name='common_in_la',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='from_duolingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infinitive',
            name='top_250',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastparticiple',
            name='infinitive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Infinitive'),
        ),
        migrations.AddField(
            model_name='gerund',
            name='infinitive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Infinitive'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='infinitive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Infinitive'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Mood'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Tense'),
        ),
    ]
