# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0005_auto_20160103_0348'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbuser',
            name='infinitives',
            field=models.ManyToManyField(to='verbs.Infinitive'),
        ),
        migrations.AddField(
            model_name='verbuser',
            name='tenses',
            field=models.ManyToManyField(to='verbs.Tense'),
        ),
    ]
