# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160103_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbuser',
            name='infinitives',
            field=models.ManyToManyField(related_query_name='infinitive_users', to='verbs.Infinitive'),
        ),
        migrations.AlterField(
            model_name='verbuser',
            name='tenses',
            field=models.ManyToManyField(related_query_name='tense_users', to='verbs.Tense'),
        ),
    ]
