# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irregular', models.BooleanField(default=False)),
                ('form_1s', models.CharField(max_length=80)),
                ('form_2s', models.CharField(max_length=80)),
                ('form_3s', models.CharField(max_length=80)),
                ('form_1p', models.CharField(max_length=80)),
                ('form_2p', models.CharField(max_length=80)),
                ('form_3p', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Gerund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerund', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Infinitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reflexive', models.BooleanField(default=False)),
                ('translation', models.CharField(max_length=125)),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('from_duolingo', models.BooleanField(default=False)),
                ('top_250', models.BooleanField(default=False)),
                ('common_in_la', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(related_query_name='infinitives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Pastparticiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastparticiple', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50)),
                ('infinitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Infinitive')),
            ],
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=50)),
                ('tense_translation', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('mood_translation', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_query_name='tenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gerund',
            name='infinitive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Infinitive'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='infinitive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Infinitive'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Tense'),
        ),
    ]
