# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infinitive',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='tense',
            old_name='translation',
            new_name='tense_translation',
        ),
    ]
