# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_auto_20160103_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infinitive',
            old_name='top_250',
            new_name='top_100',
        ),
        migrations.AddField(
            model_name='tense',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
