# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0004_auto_20160103_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infinitive',
            name='users',
        ),
        migrations.RemoveField(
            model_name='tense',
            name='users',
        ),
    ]
