# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0005_auto_20160103_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tense',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
