# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models


def set_verbs_to_active(apps, schema_editor):
    infinitives = apps.get_model("verbs", "Infinitive")

    infinitives.objects.all().update(active = True)

class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0006_tense_active'),
    ]

    operations = [
    	migrations.RunPython(set_verbs_to_active),
    ]
